import React, { useState } from 'react';
import { CheckCircle, XCircle, RotateCcw } from 'lucide-react';
import './App.css';

const OSQuiz = () => {
  const questions = [
    {
      id: 1,
      question: "Which of the following is NOT a major OS component?",
      options: ["Process Management", "Memory Management", "Compiler Design", "Storage Management"],
      correct: 2
    },
    {
      id: 2,
      question: "Bootstrap program is stored in:",
      options: ["RAM", "ROM or EEPROM", "Hard disk", "Cache memory"],
      correct: 1
    },
    {
      id: 3,
      question: "The degree of multiprogramming refers to:",
      options: ["Number of CPUs", "Number of processes in memory", "Number of users", "Number of I/O devices"],
      correct: 1
    },
    {
      id: 4,
      question: "Which interrupt is generated by the CPU itself?",
      options: ["Hardware interrupt", "Software interrupt (trap)", "External interrupt", "Timer interrupt"],
      correct: 1
    },
    {
      id: 5,
      question: "DMA (Direct Memory Access) is used for:",
      options: ["High-speed I/O devices", "CPU scheduling", "Memory allocation", "Process synchronization"],
      correct: 0
    },
    {
      id: 6,
      question: "An operating system acts as an intermediary between:",
      options: ["User and hardware", "Hardware and software", "Compiler and hardware", "Application and compiler"],
      correct: 0
    },
    {
      id: 7,
      question: "Cache memory is:",
      options: ["Faster than main memory", "Slower than main memory", "Same speed as main memory", "Faster than registers"],
      correct: 0
    },
    {
      id: 8,
      question: "What is the primary goal of an operating system?",
      options: ["To make the computer system convenient to use", "To use computer hardware efficiently", "To act as an interface between user and hardware", "To provide network services"],
      correct: 2
    },
    {
      id: 9,
      question: "Time-sharing systems primarily focus on:",
      options: ["Interactive computer system", "Batch processing", "Real-time processing", "Network services"],
      correct: 0
    },
    {
      id: 10,
      question: "System calls provide:",
      options: ["Interface to OS services", "Direct hardware access", "Compiler functions", "Database operations"],
      correct: 0
    },
    {
      id: 11,
      question: "Dual-mode operation provides:",
      options: ["Protection for the operating system", "Faster execution", "Multiple user support", "Network communication"],
      correct: 0
    },
    {
      id: 12,
      question: "In multiprogramming, the CPU switches to another job when:",
      options: ["Current job finishes", "Current job waits for I/O", "Timer expires", "User requests it"],
      correct: 1
    },
    {
      id: 13,
      question: "Privileged instructions can only be executed in:",
      options: ["User mode", "Kernel mode", "Both modes", "Protected mode only"],
      correct: 1
    },
    {
      id: 14,
      question: "A mode bit is used to:",
      options: ["Distinguish between user and kernel mode", "Control I/O operations", "Manage memory", "Schedule processes"],
      correct: 0
    },
    {
      id: 15,
      question: "Which storage is volatile?",
      options: ["RAM", "ROM", "Hard disk", "Flash memory"],
      correct: 0
    },
    {
      id: 16,
      question: "The memory hierarchy is ordered from fastest to slowest as:",
      options: ["Registers, cache, main memory, disk", "Cache, registers, main memory, disk", "Main memory, cache, registers, disk", "Disk, main memory, cache, registers"],
      correct: 0
    },
    {
      id: 17,
      question: "The main purpose of an interrupt is to:",
      options: ["Stop program execution permanently", "Signal CPU of an event requiring attention", "Transfer control to user program", "Allocate memory"],
      correct: 1
    },
    {
      id: 18,
      question: "In a computer system, protection is ensured by:",
      options: ["Hardware support only", "Operating system policies only", "Hardware and OS working together", "User programs"],
      correct: 2
    },
    {
      id: 19,
      question: "Caching is primarily used for:",
      options: ["Copying information to faster storage", "Backing up data", "Encrypting data", "Compressing data"],
      correct: 0
    },
    {
      id: 20,
      question: "Which of the following is a batch processing system?",
      options: ["Mainframe computers", "Personal computers", "Handheld computers", "Embedded systems"],
      correct: 0
    },
    {
      id: 21,
      question: "Asymmetric multiprocessing involves:",
      options: ["Master-slave relationship", "All processors equal", "No coordination needed", "Single processor only"],
      correct: 0
    },
    {
      id: 22,
      question: "Symmetric multiprocessing (SMP) means:",
      options: ["Each processor performs different tasks", "All processors are peers", "One processor is master", "Processors share no memory"],
      correct: 1
    },
    {
      id: 23,
      question: "Real-time systems are characterized by:",
      options: ["Strict time constraints", "High throughput", "Maximum CPU utilization", "Multiple users"],
      correct: 0
    },
    {
      id: 24,
      question: "A clustered system is characterized by:",
      options: ["Multiple systems working together", "Single system with multiple cores", "Virtual machines on one system", "Distributed file systems only"],
      correct: 0
    },
    {
      id: 25,
      question: "Virtual memory allows:",
      options: ["Execution of programs larger than physical memory", "Faster program execution", "Better GUI display", "Network communication"],
      correct: 0
    },
    {
      id: 26,
      question: "Hard real-time systems:",
      options: ["Must meet deadlines always", "Can tolerate some deadline misses", "Are less critical than soft real-time", "Have no timing constraints"],
      correct: 0
    },
    {
      id: 27,
      question: "The interrupt vector contains:",
      options: ["Addresses of interrupt service routines", "Interrupt priorities", "Device identifiers", "Process states"],
      correct: 0
    },
    {
      id: 28,
      question: "Spooling stands for:",
      options: ["Simultaneous Peripheral Operations On-Line", "Serial Processing Of Output Listings", "System Programming Of Operating Loops", "Standard Procedure Of Operation Loading"],
      correct: 0
    },
    {
      id: 29,
      question: "Context switch involves:",
      options: ["Saving state of current process", "Loading state of new process", "Switching between processes", "Switching users"],
      correct: 2
    },
    {
      id: 30,
      question: "A trap is caused by:",
      options: ["Hardware failure", "Error or user request", "Timer", "I/O completion"],
      correct: 1
    },
    {
      id: 31,
      question: "Which is NOT a type of system call?",
      options: ["Process control", "File management", "Compilation", "Device management"],
      correct: 2
    },
    {
      id: 32,
      question: "The operating system kernel is:",
      options: ["Always in memory", "Loaded on demand", "Stored in secondary storage", "Part of application software"],
      correct: 0
    },
    {
      id: 33,
      question: "A CPU bound process:",
      options: ["Requires more computation", "Spends more time in I/O", "Never performs I/O", "Uses only memory"],
      correct: 0
    },
    {
      id: 34,
      question: "An I/O bound process:",
      options: ["Spends more time doing I/O", "Requires more CPU time", "Never uses CPU", "Only uses disk"],
      correct: 0
    },
    {
      id: 35,
      question: "Turnaround time is:",
      options: ["Time from submission to completion", "Time in ready queue", "Time in execution", "Time in waiting"],
      correct: 0
    },
    {
      id: 36,
      question: "Throughput refers to:",
      options: ["Number of processes completed per unit time", "Time to complete a process", "CPU utilization", "Response time"],
      correct: 0
    },
    {
      id: 37,
      question: "CPU utilization should ideally be:",
      options: ["As high as possible", "As low as possible", "Around 50%", "Zero"],
      correct: 0
    },
    {
      id: 38,
      question: "Response time in interactive systems is:",
      options: ["Time from request to first response", "Total execution time", "Time to complete process", "Time in ready queue"],
      correct: 0
    },
    {
      id: 39,
      question: "NUMA (Non-Uniform Memory Access) means:",
      options: ["Access time depends on memory location", "All memory access is uniform", "No memory sharing", "Only local memory exists"],
      correct: 0
    },
    {
      id: 40,
      question: "Multicore systems have:",
      options: ["Multiple computing cores on single chip", "Multiple separate processors", "Single core with hyperthreading", "Multiple motherboards"],
      correct: 0
    },
    {
      id: 41,
      question: "Which is NOT an OS service for users?",
      options: ["Program execution", "I/O operations", "Power management", "Communication"],
      correct: 2
    },
    {
      id: 42,
      question: "Operating system services are provided for:",
      options: ["User convenience only", "System efficiency only", "User convenience and system efficiency", "Hardware management only"],
      correct: 2
    },
    {
      id: 43,
      question: "System calls are:",
      options: ["Programming interface to OS services", "Hardware instructions", "Compiler directives", "Database queries"],
      correct: 0
    },
    {
      id: 44,
      question: "A user interface can be:",
      options: ["Command-line interface (CLI)", "Graphical user interface (GUI)", "Batch interface", "Any of these types"],
      correct: 3
    },
    {
      id: 45,
      question: "The main advantage of using API rather than system calls is:",
      options: ["Program portability", "Faster execution", "Less memory usage", "Better security"],
      correct: 0
    },
    {
      id: 46,
      question: "An API (Application Programming Interface) is:",
      options: ["Set of functions available to programmers", "Hardware specification", "System call itself", "Operating system kernel"],
      correct: 0
    },
    {
      id: 47,
      question: "System call parameters can be passed by:",
      options: ["Registers", "Block or table in memory", "Stack", "Any of these methods"],
      correct: 3
    },
    {
      id: 48,
      question: "Which is a file management system call?",
      options: ["wait()", "create()", "malloc()", "signal()"],
      correct: 1
    },
    {
      id: 49,
      question: "Which is a process control system call?",
      options: ["fork()", "read()", "open()", "chmod()"],
      correct: 0
    },
    {
      id: 50,
      question: "Communication between processes can be achieved through:",
      options: ["Shared memory", "Message passing", "Either shared memory or message passing", "Files only"],
      correct: 2
    },
    {
      id: 51,
      question: "UNIX operating system structure consists of layers including:",
      options: ["Kernel at the core", "Shell at the core", "Applications at the core", "Drivers at the core"],
      correct: 0
    },
    {
      id: 52,
      question: "The MS-DOS operating system uses:",
      options: ["Single-tasking", "Multi-tasking", "Time-sharing", "Distributed processing"],
      correct: 0
    },
    {
      id: 53,
      question: "The main advantage of layered approach is:",
      options: ["Simplicity of construction", "High performance", "Less memory usage", "Faster execution"],
      correct: 0
    },
    {
      id: 54,
      question: "Layered approach in OS design means:",
      options: ["OS divided into layers", "OS divided into modules", "OS as single unit", "OS distributed across network"],
      correct: 0
    },
    {
      id: 55,
      question: "A microkernel provides:",
      options: ["Minimal process and memory management", "All OS services in kernel", "No process management", "Only file management"],
      correct: 0
    },
    {
      id: 56,
      question: "The main disadvantage of layered approach is:",
      options: ["Careful planning required", "Easy to implement", "Very modular", "Highly portable"],
      correct: 0
    },
    {
      id: 57,
      question: "Disadvantage of microkernel is:",
      options: ["Performance overhead of user-kernel communication", "Complex design", "No modularity", "Poor security"],
      correct: 0
    },
    {
      id: 58,
      question: "Benefits of microkernel include:",
      options: ["Easier to extend", "Better performance", "Less overhead", "Simpler design"],
      correct: 0
    },
    {
      id: 59,
      question: "Virtual machines provide:",
      options: ["Illusion of multiple machines", "Faster execution", "Less memory usage", "Direct hardware access"],
      correct: 0
    },
    {
      id: 60,
      question: "Loadable kernel modules:",
      options: ["Can be loaded at boot or runtime", "Must be loaded at boot only", "Cannot be unloaded", "Are not used in modern OS"],
      correct: 0
    },
    {
      id: 61,
      question: "Operating system generation (OS gen) involves:",
      options: ["Configuring OS for specific hardware", "Updating OS kernel", "Installing applications", "Creating user accounts"],
      correct: 0
    },
    {
      id: 62,
      question: "The Java Virtual Machine (JVM):",
      options: ["Executes Java bytecode", "Executes machine code", "Executes assembly code", "Executes Python code"],
      correct: 0
    },
    {
      id: 63,
      question: "GRUB is an example of:",
      options: ["Boot loader", "File system", "Shell", "System call"],
      correct: 0
    },
    {
      id: 64,
      question: "System boot process starts with:",
      options: ["Bootstrap program loading OS", "User login", "Application loading", "Network initialization"],
      correct: 0
    },
    {
      id: 65,
      question: "System programs provide:",
      options: ["Convenient environment for program development", "Kernel functions", "Hardware drivers", "Network protocols"],
      correct: 0
    },
    {
      id: 66,
      question: "A shell is:",
      options: ["Command interpreter", "Part of kernel", "Hardware component", "Device driver"],
      correct: 0
    },
    {
      id: 67,
      question: "A monolithic kernel:",
      options: ["Has all services in kernel space", "Has minimal services in kernel", "Has no services in kernel", "Uses message passing only"],
      correct: 0
    },
    {
      id: 68,
      question: "Debugging a system involves:",
      options: ["Finding and fixing errors", "Compiling programs", "Installing software", "Managing users"],
      correct: 0
    },
    {
      id: 69,
      question: "Protection mechanisms in OS:",
      options: ["Control access to resources", "Increase CPU speed", "Manage network traffic", "Compile programs"],
      correct: 0
    },
    {
      id: 70,
      question: "System calls for communication include:",
      options: ["send() and receive()", "open() and close()", "fork() and exec()", "malloc() and free()"],
      correct: 0
    },
    {
      id: 71,
      question: "The bootstrap program is the first program to run when a computer is powered on.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 72,
      question: "An operating system is a resource allocator and control program.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 73,
      question: "In multiprogramming, multiple programs are kept in memory simultaneously.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 74,
      question: "Interrupts can only be generated by hardware devices.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 75,
      question: "Time-sharing and multitasking are the same concept.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 76,
      question: "Cache memory is larger but slower than main memory.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 77,
      question: "DMA transfers data directly between I/O device and CPU registers.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 78,
      question: "Privileged instructions can be executed in user mode.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 79,
      question: "A system call changes the mode from user mode to kernel mode.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 80,
      question: "Virtual memory allows execution of processes that are not completely in memory.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 81,
      question: "In asymmetric multiprocessing, all processors are treated equally.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 82,
      question: "Symmetric multiprocessing requires special master processor.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 83,
      question: "Hard real-time systems can tolerate occasional deadline misses.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 84,
      question: "Real-time systems must complete operations within strict time constraints.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 85,
      question: "A trap is a software-generated interrupt.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 86,
      question: "Spooling allows overlap of I/O of one job with computation of another.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 87,
      question: "Context switching is overhead and does no useful work.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 88,
      question: "The kernel is the part of OS that runs in user mode.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 89,
      question: "Multicore systems have multiple processors on separate chips.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 90,
      question: "Throughput is the number of processes completed per unit time.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 91,
      question: "APIs hide the details of system calls from programmers.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 92,
      question: "System calls provide a means for user programs to request OS services.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 93,
      question: "Microkernel architecture moves services to user space.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 94,
      question: "MS-DOS was designed with a layered structure.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 95,
      question: "Virtual machines provide complete protection between system components.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 96,
      question: "Layered approach makes OS easier to debug and verify.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 97,
      question: "Loadable kernel modules are more flexible than layered approach.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 98,
      question: "System programs provide a convenient environment for program development and execution.",
      options: ["TRUE", "FALSE"],
      correct: 0
    },
    {
      id: 99,
      question: "The shell is part of the operating system kernel.",
      options: ["TRUE", "FALSE"],
      correct: 1
    },
    {
      id: 100,
      question: "A monolithic kernel is more modular than a microkernel.",
      options: ["TRUE", "FALSE"],
      correct: 1
    }
  ];

  const [answers, setAnswers] = useState({});
  const [showResults, setShowResults] = useState(false);
  const [currentPage, setCurrentPage] = useState(0);
  const questionsPerPage = 10;

  const handleAnswer = (questionId, answerIndex) => {
    setAnswers({...answers, [questionId]: answerIndex});
  };

  const handlePageChange = (newPage) => {
    setCurrentPage(newPage);
    window.scrollTo(0, 0);
  };

  const calculateScore = () => {
    let correct = 0;
    questions.forEach(q => {
      if (answers[q.id] === q.correct) correct++;
    });
    return correct;
  };

  const getWrongAnswers = () => {
    return questions.filter(q => answers[q.id] !== undefined && answers[q.id] !== q.correct);
  };

  const handleSubmit = () => {
    setShowResults(true);
    window.scrollTo(0, 0);
  };

  const handleReset = () => {
    setAnswers({});
    setShowResults(false);
    setCurrentPage(0);
  };

  const totalPages = Math.ceil(questions.length / questionsPerPage);
  const startIdx = currentPage * questionsPerPage;
  const endIdx = startIdx + questionsPerPage;
  const currentQuestions = questions.slice(startIdx, endIdx);

  if (showResults) {
    const score = calculateScore();
    const wrongAnswers = getWrongAnswers();
    const percentage = ((score / questions.length) * 100).toFixed(1);

    return (
      <div className="min-h-screen bg-gradient-to-br p-4">
        <div className="max-w-4xl">
          <div className="bg-white rounded-lg shadow-xl p-8 mb-6">
            <h1 className="text-3xl font-bold text-center text-indigo-900 mb-6">النتيجة النهائية</h1>
            
            <div className="text-center mb-8">
              <div className="text-6xl font-bold text-indigo-600 mb-2">{score}/{questions.length}</div>
              <div className="text-2xl text-gray-600">نسبة النجاح: {percentage}%</div>
              <div className={`mt-4 text-xl font-semibold ${score >= 70 ? 'text-green-600' : 'text-red-600'}`}>
                {score >= 70 ? '🎉 ممتاز! نجحت' : '❌ للأسف، محتاج تذاكر أكتر'}
              </div>
            </div>

            {wrongAnswers.length > 0 && (
              <div className="mt-8">
                <h2 className="text-2xl font-bold text-red-600 mb-4 flex items-center gap-2">
                  <XCircle className="w-6 h-6" />
                  الأسئلة اللي غلطت فيها ({wrongAnswers.length} سؤال)
                </h2>
                
                <div className="space-y-6">
                  {wrongAnswers.map((q) => (
                    <div key={q.id} className="bg-red-50 border border-red-200 rounded-lg p-4">
                      <div className="font-semibold text-gray-800 mb-3">
                        {q.id}. {q.question}
                      </div>
                      <div className="space-y-2">
                        <div className="flex items-center gap-2 text-red-600">
                          <XCircle className="w-5 h-5" />
                          <span className="font-medium">إجابتك:</span>
                          <span>{q.options[answers[q.id]]}</span>
                        </div>
                        <div className="flex items-center gap-2 text-green-600">
                          <CheckCircle className="w-5 h-5" />
                          <span className="font-medium">الإجابة الصحيحة:</span>
                          <span>{q.options[q.correct]}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <button
              onClick={handleReset}
              className="mt-8 w-full bg-indigo-600 text-white py-3 rounded-lg font-semibold transition flex items-center justify-center gap-2"
            >
              <RotateCcw className="w-5 h-5" />
              ابدأ من جديد
            </button>
          </div>
        </div>
      </div>
    );
  }

  const answeredCount = Object.keys(answers).length;

  return (
    <div className="min-h-screen bg-gradient-to-br p-4">
      <div className="max-w-4xl">
        <div className="bg-white rounded-lg shadow-xl p-6 mb-6">
          <h1 className="text-3xl font-bold text-center text-indigo-900 mb-2">Operating Systems Quiz</h1>
          <p className="text-center text-gray-600 mb-4">100 سؤال - اختبر معلوماتك في نظم التشغيل</p>
          
          <div className="bg-indigo-100 rounded-lg p-4 mb-6">
            <div className="flex justify-between items-center">
              <span className="text-indigo-800 font-semibold">تقدمك: {answeredCount}/{questions.length}</span>
              <span className="text-indigo-800 font-semibold">الصفحة: {currentPage + 1}/{totalPages}</span>
            </div>
            <div className="mt-2 bg-white rounded-full h-3 overflow-hidden">
              <div 
                className="bg-indigo-600 h-full transition"
                style={{width: `${(answeredCount / questions.length) * 100}%`}}
              />
            </div>
          </div>

          <div className="space-y-6">
            {currentQuestions.map((q) => (
              <div key={q.id} className="border border-gray-200 rounded-lg p-4 transition">
                <div className="font-semibold text-gray-800 mb-3">
                  {q.id}. {q.question}
                </div>
                <div className="space-y-2">
                  {q.options.map((option, idx) => (
                    <label
                      key={idx}
                      className={`flex items-center p-3 rounded-lg cursor-pointer transition ${
                        answers[q.id] === idx
                          ? 'bg-indigo-100 border-2 border-indigo-500'
                          : 'bg-gray-50 border border-gray-200'
                      }`}
                    >
                      <input
                        type="radio"
                        name={`q${q.id}`}
                        checked={answers[q.id] === idx}
                        onChange={() => handleAnswer(q.id, idx)}
                        className="w-4 h-4"
                      />
                      <span className="ml-3 text-gray-700">{option}</span>
                    </label>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="flex gap-4 mt-6">
            {currentPage > 0 && (
              <button
                onClick={() => handlePageChange(currentPage - 1)}
                className="flex-1 bg-gray-200 text-gray-800 py-3 rounded-lg font-semibold transition"
              >
                السابق
              </button>
            )}
            
            {currentPage < totalPages - 1 ? (
              <button
                onClick={() => handlePageChange(currentPage + 1)}
                className="flex-1 bg-indigo-600 text-white py-3 rounded-lg font-semibold transition"
              >
                التالي
              </button>
            ) : (
              <button
                onClick={handleSubmit}
                disabled={answeredCount < questions.length}
                className={`flex-1 py-3 rounded-lg font-semibold transition ${
                  answeredCount < questions.length
                    ? 'bg-gray-300 text-gray-500'
                    : 'bg-green-600 text-white'
                }`}
              >
                {answeredCount < questions.length 
                  ? `أجب على كل الأسئلة (${answeredCount}/${questions.length})`
                  : 'اعرض النتيجة'
                }
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default OSQuiz;